import { SomHelmet } from "./types/item";

export const helmets: SomHelmet[] = [
  {
    id: "fur-hat",
    name: "Fur Hat",
    description: "",
    imageUrl: "/pictures/item36.png",
    requiredStats: {
      level: 1,
      speed: 3,
    },
    durability: 65,
  },
  {
    id: "bandana",
    name: "Bandana",
    description: "",
    imageUrl: "/pictures/item76.png",
    requiredStats: {
      level: 1,
      speed: 6,
    },
    durability: 80,
  },
  {
    id: "bronze",
    name: "Bronze Helm",
    description: "",
    imageUrl: "/pictures/item35.png",
    requiredStats: {
      level: 1,
      speed: 12,
    },
    durability: 100,
  },
  {
    id: "tiger-mask",
    name: "Tiger Mask",
    description: "",
    imageUrl: "/pictures/item14.png",
    requiredStats: {
      level: 1,
      speed: 20,
    },
    durability: 115,
  },
  {
    id: "mouse-princes-crown",
    name: "Mouse Prince's Crown",
    description: "",
    imageUrl: "/pictures/item80.png",
    requiredStats: {
      level: 1,
      speed: 24,
    },
    durability: 122,
  },
  {
    id: "holy",
    name: "Holy Helmet",
    description: "",
    imageUrl: "/pictures/item114.png",
    requiredStats: {
      level: 1,
      speed: 25,
    },
    durability: 135,
  },
  {
    id: "hsv",
    name: "Hellslayer's Visuar",
    description: "",
    imageUrl: "/pictures/item91.png",
    requiredStats: {
      level: 1,
      speed: 35,
    },
    durability: 145,
  },
  {
    id: "helmush",
    name: "Helmush",
    description: "",
    imageUrl: "/pictures/item677.png",
    requiredStats: {
      level: 1,
      speed: 40,
    },
    durability: 150,
  },
  {
    id: "hood-of-mana",
    name: "Hood of Mana",
    description: "",
    imageUrl: "/pictures/item202.png",
    requiredStats: {
      level: 1,
      speed: 40,
    },
    durability: 160,
  },
  {
    id: "jb",
    name: "Jeweled Bandana",
    description: "",
    imageUrl: "/pictures/item571.png",
    requiredStats: {
      level: 1,
      speed: 45,
    },
    durability: 180,
  },
  {
    id: "ch",
    name: "Cold Helmet",
    description: "",
    imageUrl: "/pictures/item38.png",
    requiredStats: {
      level: 1,
      speed: 50,
    },
    durability: 215,
  },
  {
    id: "ah",
    name: "Ancient Helm",
    description: "",
    imageUrl: "/pictures/item34.png",
    requiredStats: {
      level: 1,
      speed: 65,
    },
    durability: 210,
  },
  {
    id: "ec",
    name: "Elven Cap",
    description: "",
    imageUrl: "/pictures/item4.png",
    requiredStats: {
      level: 1,
      speed: 70,
    },
    durability: 228,
  },
  {
    id: "zb",
    name: "Zodiac Basinet",
    description: "",
    imageUrl: "/pictures/item197.png",
    requiredStats: {
      level: 1,
      speed: 75,
    },
    durability: 250,
  },
  {
    id: "skeletal-casque",
    name: "Skeletal Casque",
    description: "",
    imageUrl: "/pictures/item579.png",
    requiredStats: {
      level: 1,
      speed: 100,
    },
    durability: 300,
  },
  {
    id: "conq",
    name: "Conqueror's Helm",
    description: "",
    imageUrl: "/pictures/item140.png",
    requiredStats: {
      level: 1,
      speed: 106,
    },
    durability: 285,
  },
  {
    id: "whh",
    name: "War Hero's Helmet",
    description: "",
    imageUrl: "/pictures/item37.png",
    requiredStats: {
      level: 1,
      speed: 125,
    },
    durability: 300,
  },
  {
    id: "halo",
    name: "Halo",
    description: "",
    imageUrl: "/pictures/item103.png",
    requiredStats: {
      level: 1,
      speed: 150,
    },
    durability: 300,
  },
  {
    id: "cestrum",
    name: "Cestrum",
    description: "",
    imageUrl: "/pictures/item198.png",
    requiredStats: {
      level: 1,
      speed: 155,
    },
    durability: 325,
  },
  {
    id: "crown-of-glacier",
    name: "Crown of Glacier",
    description: "",
    imageUrl: "/pictures/item118.png",
    requiredStats: {
      level: 1,
      speed: 160,
    },
    durability: 400,
  },
  {
    id: "ohb",
    name: "Ohka Headband",
    description: "",
    imageUrl: "/pictures/item572.png",
    requiredStats: {
      level: 1,
      speed: 175,
    },
    durability: 450,
  },
  {
    id: "rmc",
    name: "Royal Mirage Crown",
    description: "",
    imageUrl: "/pictures/item616.png",
    requiredStats: {
      level: 1,
      speed: 195,
    },
    durability: 500,
  },
  {
    id: "rmc",
    name: "Royal Mirage Crown",
    description: "",
    imageUrl: "/pictures/item616.png",
    requiredStats: {
      level: 1,
      speed: 195,
    },
    durability: 500,
  },
  {
    id: "mordreds-crown",
    name: "Mordred's Crown",
    description: "",
    imageUrl: "/pictures/item561.png",
    requiredStats: {
      level: 1,
      speed: 265,
    },
    durability: 530,
  },
  {
    id: "maze-prize",
    name: "Maze Prize Helm",
    description: "",
    imageUrl: "/pictures/item571.png",
    requiredStats: {
      level: 1,
      speed: 275,
    },
    durability: 690,
  },
  {
    id: "coveted-cestrum",
    name: "Coveted Cestrum",
    description: "",
    imageUrl: "/pictures/item198.png",
    requiredStats: {
      level: 1,
      speed: 310,
    },
    durability: 2500,
  },
  {
    id: "lunar-kazail",
    name: "Lunar Kazail Helm",
    description: "",
    imageUrl: "/pictures/item673.png",
    requiredStats: {
      level: 1,
      speed: 350,
    },
    durability: 900,
  },
  {
    id: "upgraded-maze-prize",
    name: "Maze Prize Helm (Upgraded)",
    description: "",
    imageUrl: "/pictures/item571.png",
    unique: true,
    requiredStats: {
      level: 1,
      speed: 350,
    },
    durability: 900,
  },
  {
    id: "guardians",
    name: "Guardian's Helm",
    description: "",
    imageUrl: "/pictures/item200.png",
    requiredStats: {
      level: 300,
      speed: 400,
    },
    durability: 1000,
  },
  {
    id: "vwh",
    name: "Viking War Helmet",
    description: "",
    imageUrl: "/pictures/item237.png",
    requiredStats: {
      level: 1,
      speed: 400,
    },
    durability: 1000,
  },
  {
    id: "dh",
    name: "Dragon Helmet",
    description: "",
    imageUrl: "/pictures/item37.png",
    requiredStats: {
      level: 1,
      speed: 400,
    },
    durability: 1000,
  },
  {
    id: "rgh",
    name: "Reinforced Guardian Helm",
    description: "",
    imageUrl: "/pictures/item336.png",
    requiredStats: {
      level: 1,
      speed: 420,
    },
    durability: 1050,
  },
  {
    id: "hog",
    name: "Helm of Glory",
    description: "",
    imageUrl: "/pictures/item645.png",
    requiredStats: {
      level: 300,
      speed: 450,
    },
    durability: 1500,
  },
  {
    id: "fhog",
    name: "Fortified Helm of Glory",
    description: "",
    imageUrl: "/pictures/item648.png",
    requiredStats: {
      level: 300,
      speed: 500,
    },
    durability: 1500,
  },
  {
    id: "vwhp",
    name: "Viking War Helmet+",
    description: "",
    imageUrl: "/pictures/item237.png",
    requiredStats: {
      level: 1,
      speed: 500,
    },
    durability: 1650,
  },
  {
    id: "dhp",
    name: "Dragon Helmet+",
    description: "",
    imageUrl: "/pictures/item37.png",
    requiredStats: {
      level: 1,
      speed: 500,
    },
    durability: 1650,
  },
  {
    id: "vbh",
    name: "Viking Battle Helm",
    description: "",
    imageUrl: "/pictures/item237.png",
    requiredStats: {
      level: 1,
      speed: 600,
    },
    durability: 1900,
  },
  {
    id: "udh",
    name: "Undead Dragon Helm",
    description: "",
    imageUrl: "/pictures/item560.png",
    requiredStats: {
      level: 1,
      speed: 600,
    },
    durability: 1900,
  },
  {
    id: "mal",
    name: "Maleficent Helm",
    description: "",
    imageUrl: "/pictures/item532.png",
    requiredStats: {
      level: 1,
      speed: 650,
    },
    durability: 1650,
  },
  {
    id: "rmal",
    name: "Reinforced Maleficent Helm",
    description: "",
    imageUrl: "/pictures/item532.png",
    requiredStats: {
      level: 1,
      speed: 650,
    },
    durability: 3900,
  },
];
