import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-950 text-slate-50`}>
        <div className="min-h-screen flex flex-col max-w-7xl mx-auto">
          <Navbar />
          <main className="flex-grow flex flex-col items-center justify-between p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
